nginxHtmlHostPath: /var/next-oknesset/nginx-html
letsEncryptLogHostPath: /var/next-oknesset/letsencrypt-log
letsencryptEtcHostPath: /var/next-oknesset/letsencrypt-etc
secureServerName: next.oknesset.org
locations80: |
    include /etc/nginx/conf.d/data.inc;
    location / {
        return 301 https://next.oknesset.org$request_uri;
    }
locations443: |
    include /etc/nginx/conf.d/data.inc;
    location /pipelines/ {
        proxy_pass http://app:5000/;
    }
    location /adminer/ {
        proxy_pass http://adminer:8080;
        include /etc/nginx/conf.d/restricted.inc;
    }
    location /flower/ {
        rewrite ^/flower/(.*)$ /$1 break;
        proxy_pass http://flower:5555;
        proxy_set_header Host $host;
        include /etc/nginx/conf.d/restricted.inc;
    }
    location /metabase/ {
        proxy_pass http://metabase:3000/;
    }
    location /committees/ {
        rewrite ^/committees/(.*)$ /$1 break;
        proxy_pass http://committees-webapp:5050;
        proxy_set_header Host $host;
    }
    location /grafana/ {
        rewrite ^/grafana/(.*)$ /$1 break;
        proxy_pass http://grafana:3000;
        proxy_set_header Host $host;
    }
