version: "3"

services:

  app:
    # you can disable a service using the following line
    # command: echo "service disabled"
    environment:
      # you can set to 0 to disable worker but still run in docker and use the dashboard
      - "DPP_WORKER_CONCURRENCY=0"

  # additional optional services

  ## adminer (formerly PhpMyAdmin) - web UI for DB access
  # adminer:
  #   image: adminer:4.3.1-standalone
  #   ports:
  #     - "18080:8080"

## provides multiple paths on https://next.oknesset.org/
## e.g. https://next.oknesset.org/pipelines/ https://next.oknesset.org/data/
#  nginx:
#    build: devops/nginx
#    image: knesset-data/nginx
#    ports:
#      - "80:80"
#      - "12443:12443"
#    volumes:
#      - .data-docker/nginx-html:/usr/share/nginx/html/
#      - .data-docker:/knesset-data-pipelines

## issue certificates using letsencrypt
#  letsencrypt:
#    build: devops/letsencrypt
#    image: knesset-data/letsencrypt
#    volumes:
#      - .data-docker/letsencrypt/log:/var/log/letsencrypt
#      - .data-docker/letsencrypt/etc:/etc/letsencrypt
#      - .data-docker/nginx-html:/nginx-html