version: "3"

# services:

  # app:
    # you can disable a service using the following line
    # command: echo "service disabled"
    # environment:
      # - "DPP_WORKER_CONCURRENCY=1"
      # - "DPP_INFLUXDB_URL=http://influxdb:8086"
      # - "DPP_INFLUXDB_DB=dpp"

  # additional optional services

## Metabase - DB UI
#  metabase:
#    image: metabase/metabase
#    depends_on: ["db"]
#    ports: ["13000:3000"]
#    environment:
#      - MB_DB_TYPE=postgres
#      # you need to create the db first, something like this:
#      # docker-compose exec db sudo -i -u postgres psql -c "CREATE DATABASE metabase;"
#      - MB_DB_DBNAME=metabase
#      - MB_DB_PORT=5432
#      - MB_DB_USER=postgres
#      - MB_DB_PASS=123456
#      - MB_DB_HOST=db

## InfluxDB - time series DB for metrics
#  influxdb:
#    image: influxdb:1.3-alpine
#    ports: ["18086:8086"]
    # volumes:
    # - .data-docker/influxdb:/var/lib/influxdb

## Grafana - Graphing UI over InfluxDB
#  grafana:
#    image: grafana/grafana
    # default username/password = admin/admin
#    ports: ["13030:3000"]
#
#  autoscaler:
#    build: devops/app_autoscaler
#    environment:
#    - "DPP_AUTOSCALER_INTERVAL=5"
#    - "DPP_PIPELINES_URL=https://next.oknesset.org/pipelines"
#    - "DPP_AUTOSCALER_REPO=OriHoch/knesset-data-pipelines"
#    - "DPP_AUTOSCALER_USER=oknesset-deployment-bot"
#    - "DPP_AUTOSCALER_EMAIL=knesset-data-production-autoscaler@next.oknesset.org"
#    - "DPP_AUTOSCALER_BRANCH=master"
#    - "DPP_AUTOSCALER_TOKEN=16922807c3fe63e0b9b3c61eae67bb91547718a2"
#    - "DPP_PROVISION_VALUES_FILE=devops/k8s/values-production-provision.yaml"

#  ssh-socks-proxy:
#    image: orihoch/ssh-socks-proxy@sha256:94faea572a5ff570d3dea92ca381909603e488c4162f36e56416648647ffd263
#    ports: ["8123:8123"]
#    environment:
#    - "SSH_HOST=ubuntu@db1.oknesset.org"
#    - "SSH_PORT=22"
#    - "SOCKS_PORT=8123"
#    - "SSH_B64_KEY="
#    - "SSH_B64_PUBKEY="
