version: "2"

services:
  data:
    image: tianon/true
    volumes:
      - ./:/knesset
      
  db:
    build: docker/postgresql
    volumes_from:
      - data
    ports:
      - "15432:5432"
    environment:
      - PG_PASSWORD

  redis:
    build: docker/redis

  minio:
    build: docker/minio
    ports:
      - "9000:9000"
    volumes_from:
      - data
    command:
      - server
      - /data
    environment:
      - MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY

  app:
    build: docker/knesset
    image: knesset-data/pipelines
    volumes_from:
      - data
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    environment:
      - DPP_REDIS_HOST
      - DPP_DB_ENGINE
      - DPP_WORKER_CONCURRENCY