version: "3"

# services:

  # app:
    # you can disable a service using the following line
    # command: echo "service disabled"
    # environment:
      # - "DPP_WORKER_CONCURRENCY=1"
      # - "DPP_INFLUXDB_URL=http://influxdb:8086"
      # - "DPP_INFLUXDB_DB=dpp"

  # additional optional services

## Metabase - DB UI
#  metabase:
#    image: metabase/metabase
#    depends_on: ["db"]
#    ports: ["13000:3000"]
#    environment:
#      - MB_DB_TYPE=postgres
#      # you need to create the db first, something like this:
#      # docker-compose exec db sudo -i -u postgres psql -c "CREATE DATABASE metabase;"
#      - MB_DB_DBNAME=metabase
#      - MB_DB_PORT=5432
#      - MB_DB_USER=postgres
#      - MB_DB_PASS=123456
#      - MB_DB_HOST=db

## InfluxDB - time series DB for metrics
#  influxdb:
#    image: influxdb:1.3-alpine
#    ports: ["18086:8086"]
    # volumes:
    # - .data-docker/influxdb:/var/lib/influxdb

## Grafana - Graphing UI over InfluxDB
#  grafana:
#    image: grafana/grafana
    # default username/password = admin/admin
#    ports: ["13030:3000"]
