{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{.Values.letsEncryptName | default "letsencrypt"}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.letsEncryptName | default "letsencrypt"}}
    spec:
      containers:
      - name: {{.Values.letsEncryptName | default "letsencrypt"}}
        image: {{.Values.letsEncryptImage | default "orihoch/datapackage-pipelines-plus-plus-letsencrypt:v0.0.1"}}
        resources:
          requests:
            cpu: {{.Values.letsEncryptCpuRequests | default "1m"}}
        volumeMounts:
        - name: host
          mountPath: /var/log/letsencrypt
          subPath: {{ .Values.global.hostPathLetsencryptLogSubPath }}
        - name: host
          mountPath: /etc/letsencrypt
          subPath: {{ .Values.global.hostPathLetsencryptEtcSubPath }}
        - name: host
          mountPath: /nginx-html
          subPath: {{ .Values.global.hostPathNginxHtmlSubPath }}
      volumes:
      - name: host
        hostPath:
          path: {{ .Values.global.hostPath }}
{{ end }}