{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name | default "redis"}}
spec:
  selector:
    app: {{.Values.name | default "redis"}}
  ports:
  - name: "6379"
    port: 6379
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.name | default "redis"}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.name | default "redis"}}
    spec:
{{ include "app-workers-anti-affinity" . | indent 6}}
      containers:
      - name: {{.Values.name | default "redis"}}
        image: {{.Values.image | default "redis:alpine"}}
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: {{.Values.cpuRequests | default "0.001"}}
            memory: {{.Values.memoryRequests | default "20Mi" | quote}}
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 1
          timeoutSeconds: 1
          tcpSocket:
            port: 6379
{{ end }}
