{{ if .Values.enableAutoscaler }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-autoscaler
spec:
  replicas: 1
  strategy: {type: Recreate}
  template:
    metadata:
      labels:
        app: app-autoscaler
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.global.gkeNodePool | default "default-pool" | quote }}
      containers:
      - name: app-autoscaler
        image: {{.Values.autoscalerImage | quote}}
        env:
        - {name: "DPP_AUTOSCALER_INTERVAL", "value": {{ .Values.autoscalerInterval | quote }}}
        - {name: "DPP_PIPELINES_URL", "value": {{ .Values.autoscalerPipelinesUrl | quote }}}
        - {name: "DPP_AUTOSCALER_REPO", "value": {{ .Values.autoscalerRepo | quote }}}
        - {name: "DPP_AUTOSCALER_USER", "value": {{ .Values.autoscalerGitUser | quote }}}
        - {name: "DPP_AUTOSCALER_EMAIL", "value": {{ .Values.autoscalerGitEmail | quote }}}
        - {name: "DPP_AUTOSCALER_BRANCH", "value": {{ .Values.autoscalerBranch | quote }}}
        - {name: "DPP_AUTOSCALER_TOKEN", "valueFrom": {secretKeyRef: {name: {{.Values.global.secretEnvVars | quote}}, key: "AUTOSCALER_GITHUB_TOKEN"}}}
        - {name: "DPP_PROVISION_VALUES_FILE", value: {{ .Values.autoscalerValuesFile | quote }}}
        resources:
          requests:
            cpu: 0.001
            memory: "10Mi"
          limits:
            cpu: 0.05
            memory: "100Mi"
{{ end }}
