apiVersion: v1
kind: Service
metadata: {name: committees-webapp}
spec:
  ports:
  - {name: '5050', port: 5050}
  selector: {app: committees-webapp}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: committees-webapp}
spec:
  replicas: 1
  template:
    metadata:
      labels: {app: committees-webapp}
    spec:
      containers:
      - env:
        - name: DPP_DB_ENGINE
          valueFrom:
            configMapKeyRef: {key: DPP_DB_ENGINE, name: configmap}
        image: gcr.io/hasadna-oknesset/knesset-data-committees-webapp:3f10df07be6ac02929d38c008f8ce1989dd28a51
        name: committees-webapp
        ports:
        - {containerPort: 5050}
        resources:
          requests: {cpu: 5m}
