# this claim was applied before moving to helm, so has to be applied manually
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knesset-data-influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
