apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metabase
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - env:
        - {name: "MB_DB_TYPE", value: "postgres"}
        # you need to create the db first, something like this:
        # kubectl exec -it db-87339143-v3mpl -- sudo -i -u postgres psql -c "CREATE DATABASE metabase;"
        - {name: "MB_DB_DBNAME", value: "metabase"}
        - {name: "MB_DB_PORT", value: "5432"}
        - {name: "MB_DB_USER", value: "postgres"}
        - {name: "MB_DB_PASS", valueFrom: {configMapKeyRef: {name: configmap, key: PG_PASSWORD}}}
        - {name: "MB_DB_HOST", value: "db"}
        image: metabase/metabase
        name: metabase
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  selector:
    app: metabase
  ports:
  - name: "3000"
    port: 3000
