# this service was applied before moving to helm, so has to be applied manually
apiVersion: v1
kind: Service
metadata: {name: nginx}
spec:
  ports:
  - {name: '80', port: 80}
  - {name: '443', port: 443}
  selector: {app: nginx}
  type: LoadBalancer
