committees:
  enabled: true
letsencrypt:
  enabled: true
nginx:
  enabled: true
  enableCommittees: true
  enableGrafana: true
  enableMetabase: true
  minioSslDomain: "minio.oknesset.org"
  htpasswdSecretName: nginx-htpasswd
  sslDomain: next.oknesset.org
db:
  gcePersistentDiskName: "knesset-data-pipelines-production-db"
  backupUploadProjectId: hasadna-oknesset
  backupUploadZone: us-central1-a
  backupUploadServiceAccountId: kdp-production-db-backups@hasadna-oknesset.iam.gserviceaccount.com
  backupUploadServiceAccountKeySecret: db-backup-upload-google-key
  backupUploadBucketName: kdp-production-db-backups
jobs:
  restoreDbJobName: db-restore-17-10-05-15-55
  restoreDbGsUrl: gs://kdp-production-db-backups/17-10-05-09-12.sql
  restoreDbServiceAccountId: kdp-production-db-backups@hasadna-oknesset.iam.gserviceaccount.com
  restoreDbProjectId: hasadna-oknesset
  restoreDbZone: us-central1-a
  restoreDbServiceAccountKeySecret: db-backup-upload-google-key
global:
  skipInitContainers: true
  rootUrl: https://next.oknesset.org
app:
  dppWorkerConcurrency: 2
  dppWorkerReplicas: 1
  cpuRequests: 0.4
  memoryRequests: "500Mi"
  influxDb: dpp
influxdb:
  enabled: true
  gcePersistentDiskName: "knesset-data-pipelines-production-influxdb"
grafana:
  enabled: true
metabase:
  enabled: true
minio:
  gcePersistentDiskName: "knesset-data-pipelines-production-minio"
flower:
  urlPrefix: flower
