{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name | default "nginx" | quote}}
spec:
  ports:
  - port: 80
    name: "80"
  {{ if .Values.sslDomain }}
  - port: 443
    name: "443"
  {{ end }}
  selector: {app: {{.Values.name | default "nginx" | quote}}}
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata: {name: {{.Values.name | default "nginx" | quote}}}
spec:
  replicas: 1
  template:
    metadata:
      labels: {app: {{.Values.name | default "nginx" | quote}}}
    spec:
      containers:
      - image: {{.Values.image | default "nginx:alpine" | quote}}
        name: {{.Values.name | default "nginx" | quote}}
        ports:
        - {containerPort: 80}
        {{ if .Values.sslDomain }}
        - {containerPort: 443}
        {{ end }}
        resources:
          requests:
            cpu: {{.Values.cpuRequests | default "0.005"}}
            memory: {{.Values.memoryRequests | default "10Mi"}}
        volumeMounts:
        - name: nginx-conf-d
          mountPath: /etc/nginx/conf.d
          readOnly: true
        {{ if .Values.htpasswdSecretName }}
        - name: nginx-htpasswd
          mountPath: /etc/nginx/htpasswd
          readOnly: true
        {{ end }}
        - name: host
          mountPath: /etc/letsencrypt
          subPath: "letsencrypt-etc"
        - name: host
          mountPath: /usr/share/nginx/html
          subPath: "nginx-html"
      volumes:
      - name: nginx-conf-d
        configMap:
          name: {{.Values.configMapName | default "nginx-conf-d" | quote}}
      {{ if .Values.htpasswdSecretName }}
      - name: nginx-htpasswd
        secret:
          secretName: {{ .Values.htpasswdSecretName }}
      {{ end }}
      - name: host
        hostPath:
          path: "/var/shared-host-path"
{{ end }}
